<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-4D96T8D" failures="1" tests="5" name="Personal loan" time="0.296" errors="0" timestamp="26 Jun 2024 13:47:34 GMT">
  <testcase classname="frameworkTestNGSec16.day1" name="Demo" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at frameworkTestNGSec16.day1.Demo(day1.java:22)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="frameworkTestNGSec16.day2" name="ploan" time="0.012"/>
  <testcase classname="frameworkTestNGSec16.day4" name="LoginAPIHomeLoan" time="0.013"/>
  <testcase classname="frameworkTestNGSec16.day4" name="MobileLoginHomeLoan" time="0.046"/>
  <testcase classname="frameworkTestNGSec16.day4" name="WebloginHomeLoan" time="0.014"/>
</testsuite> <!-- Personal loan -->
